#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TipPro.Android.Resource", IsApplication=true)]

namespace TipPro.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnCalculate = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int btnExit = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int btnNext = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int lblClose = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int lblComment = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int lblPercent = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int lblQuestion = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int lblTip = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int seekBarPercent = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int txtCost = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Percent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Total = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ass = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cheap = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fair = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int good = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int great = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int mega = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int ultra = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
